[[Overview]]
== Overview

[NOTE]
.Instructions
====
This 4-overview.adoc file helps the reader to better understand the various sections of the ER. It should be written like an extended table of contents.
====

== Feature Encoding
=== Current version encoding
This section describes the goods and bads of the current encoding.

The current proposed encoding is a direct translation of the GeoJSON Encoding into XML.

=== Alternative feature encodings

Three alternatives are presented below. All three rely on the use of microdata to specify the non-geometrical properties of the feature. The way the encode geometry is different.
We have to better discuss about the actual CRS used for the features. For the moment I'm assuming extent coordinates.
Since MapML is intended for representing 2D maps, I'm only considering 2D coordinates.

=== Alternative 1: Compact geometry encoding with microdata
This encoding is departing form the general feature model where a feature can have geopmetrical and non-geometrical properties at the same level. Instead, it assumes that the content of a feature is characterized by its geometrical properties first and non-geometrical properties can be attached to it as subproperties. The advantage of this approach is that we can attach non-geometrical properties to the complete geometry but also to any part of it.

In this encoding root feature elements are named <polygon>, <polyline>... that. Inside this elements,  html text is included describing the feature. We are using microdata to include tag the html text with semantics. In addition, We are introducing the linearRing element that includes the coordinates of the polygon.

The style of the polygon applies to all linearRigns but can be overwritten by one of them. It does on apply to the non-geometrical properties that should define their one styles.

.Example of a polygon encoding
[source,html]
----
<mapml>
  <polygon id="myrestaurant" style="fill:red;stroke:black;stroke-width:3;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <linearRing boundary="exterior">123,321 124,322 126,322 123,321</linearRing>
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
  </polygon>
</mapml>
----

The following example shows how se can add non-geometrical properties to an inner ring.

.Example of a polygon with a ring of a different color and additional non-geometrical properties.
[source,html]
----
<mapml>
  <polygon id="myrestaurant" style="fill:red;stroke:black;stroke-width:3;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <linearRing boundary="exterior">123,321 124,322 126,322 123,321</linearRing>
    <linearRing boundary="interior" style="stroke:orange;stroke-width:5">123.5,321.5 124.5,322.5 125.5,321.5 123.5,321.5
      <p itemprop="description">Hole in the restaurant land.</p>
    </linearRing>
  </polygon>
</mapml>
----

=== Alternative 2: Compact geometry encoding with microdata

.Example of a polygon encoding
[source,html]
----
<mapml>
  <feature id="myrestaurant" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <polygon id="MyRestaurantGeometry" style="fill:red;stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://pending.schema.org/GeospatialGeometry">
      <linearRing boundary="exterior">123,321 124,322 126,322 123,321</linearRing>
    </polygon>
  </feature>
</mapml>
----

=== Alternative 3: GML geometry encoding with microdata
The following encoding reuses GML geometrical classes to encode the geometrical properties. In this case, there is neither namespace nor GML schema but only the reuse of the GML encoding of geometrical features. We are also eliminating the need for defining feature types a priori.The resulting notation is not terrible in terms of size compared to the other more compact alternatives.

Since we have relaxed GML validation, we can consider that GML elements are extensible and we can add attributes and element when needed. One of our additions is the inclusion of style to represent how the objects need to be portrait in the screen. In the following examples we use the style property. We could also use the other approaches to associate styles to elements in HTML such as the use of "class" names or the association of styles to element id's.

[NOTE]
====
The use of SVG (css) styles in GML is not new and was introduced in GML 3.0.0 and still present in the informative annex H in GML 3.2.1. Nevertheless, the encoding suggested here is different and based on how HTML links elements with css styles.
====

.Example of a polygon encoding
[source,html]
----
<mapml>
  <feature id="myrestaurant" style="stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <Polygon id="MyRestaurantGeometry" style="fill:lime;stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://www.opengis.net/gml/3.2">
      <exterior>
        <LinearRing>
          <posList>123 321 124 322 126 322 123 321
          </posList>
        </LinearRing>
      </exterior>
    </Polygon>
  </feature>
</mapml>
----

In this example, we making use of the relaxation of GML validation to include new style attribute to in inner ring and to add non-geometrical properties to it.

.Example of a polygon encoding with holes
[source,html]
----
<mapml>
  <feature id="myrestaurant" style="stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <Polygon id="MyRestaurantGeometry" style="fill:lime;stroke:black;stroke-width:3;opacity:0.5" itemscope itemtype="http://www.opengis.net/gml/3.2">
      <exterior>
        <LinearRing>
          <posList>123 321 124 322 126 322 123 321
          </posList>
        </LinearRing>
      </exterior>
      <interior style="stroke:orange;stroke-width:5">
        <LinearRing>
          <posList>123.5 321.5 124.5 322.5 125.5 321.5 123.5 321.5
          </posList>
        </LinearRing>
        <span itemscope itemtype="http://schema.org/Thing">
          <p itemprop="description">Hole in the restaurant land.</p>
        </span>
      </interior>
    </Polygon>
  </feature>
</mapml>
----

If we opt for this approach, we should detail what extensions are allowed in the specification. In addition, we could need some addition to GML objects, such as the addition of ellipses.

== Other
(( Example: ))

(( Section 5 introduces the problem of vector tiling. It describes the situation prior to the testbed and discusses the requirements set by the sponsors. ))

(( Section 6 discusses the mathematical model behind the various tiling strategies. It provides recommendations on preferred strategies. ))

(( Section 7 presents the solution developed in this testbed. A clear mapping of requirements to solutions is provided. The section shows additional work is required to implement 3D tiles, which could not be addressed in this activity. ))

(( Section 8 provides a summary of the main findings and discusses links to other tasks such as WFS 3.0 and WMTS 2.3. ))

(( Annex A provides code snippets that illustrate the functionality of the Vector Tiling Engine and shall help to implement similar technology. It briefly discusses the key issues we experienced during implementation.))
