[[features]]
== Feature Encoding

=== MapML in relation to other feature encodings
MapML is unique relative to other encodings but the concern that it is duplicative in some way. It is trying to apply geospatial information on the Web best practices, and adapting them to users where applicable.

The requirements for MapML were originally developed and published on the Web here: http://maps4html.github.io/HTML-Map-Element-UseCases-Requirements. MapML is an extension to HTML, which if implemented, implies that the browser understands map / layer semantics (however those elements are eventually named), as well as feature / property / geometry semantics. As such it is intended to be a user-oriented format. For example, today on the Web, users create Web pages in all manner of styles, but the common denominator is HTML and CSS and possibly JavaScript for progressive enhancement. Today, there is no map / layer behavior, much less feature / property / geometry semantics, in the browser (proof: try disabling JavaScript, then go to Google Maps). MapML provides the ability to encode map / layer and feature / property / geometry semantics in one (simple) format that will be read and interpreted by browsers directly. It is user-oriented, to the extent this is possible for maps. But it brings geographic knowledge to the browser, and it's the browser that is our user agent.

There is no other encoding or service that attempts to do this. If GeoJSON, or GML, or KML was suitable, browsers would have implemented or be able to implement those directly. MapML should not be constrained by those other encodings should the need for user-oriented features arise (e.g. markup in coordinate strings and possibly other requirements). A major objective of MapML is to make the browser understand not only where the user is (GeoLocation API, https://www.w3schools.com/html/html5_geolocation.asp), but also to understand where features are in relation to the user (MapML should achieve this).

Take, for example vector tiles. Vector tiles are an 'unknown media type' as far as the browser is concerned.  As such, they are handled by the JavaScript layer, which is to say, not by the browser, except for through the canvas API calls by the JavaScript.  Vector tiles are even less interoperable than png tiles, since the browser engine 'understands' how to layout and paint png and other image formats.  Their main advantage is bandwidth conservation, which is important, but it's not the first step in standardization of geospatial concepts in the browser.

MapML is not overlapping or duplicating vector tiles.  However, a MapML client engine, whether it was implemented in JavaScript, or WASM, or preferably by the browser, could use vector tiles to paint a map layer.  The main issue I see with that is the standardization of the tile format to the point where its as widely understood and implemented as png (say), but that may eventually happen.  Finally, despite the canvas element, vector tiles styling is done using scripting, because they are not DOM related in that sense, hence not susceptible to styling via CSS. i.e. not a standard yet.

Regarding the WFS 3 initiative: who is it for?  Web devs?  If so, just add a GeoJSON format to the output and it will work better, without changing the whole W*S model. If it's for users, we should consider what users, and possibly talk about including MapML as the default output format.  I think this could be done even without changing the whole W*S model, and we would leverage infrastructure in place.  MapML is trying to change the way we see the world, not how the world is. Browser developers call this “paving the cow paths”. WFS 3 is trying to change how the world is, which is fraught and unlikely to succeed.  See also Tim Berners-Lee on the Test of Independent Invention.

[NOTE]
.Instructions
====
This 4-overview.adoc file helps the reader to better understand the various sections of the ER. It should be written like an extended table of contents.
====

== Feature Encoding
=== Current version encoding
This section describes the goods and bads of the current encoding.

The current proposed encoding is a direct translation of the GeoJSON Encoding into XML.

=== Alternative feature encodings

Three alternatives are presented below. All three rely on the use of microdata to specify the non-geometrical properties of the feature. The way the encode geometry is different.
We have to better discuss about the actual CRS used for the features. For the moment I'm assuming extent coordinates.
Since MapML is intended for representing 2D maps, I'm only considering 2D coordinates.

=== Alternative 1: Compact geometry encoding with microdata
This encoding is departing form the general feature model where a feature can have geopmetrical and non-geometrical properties at the same level. Instead, it assumes that the content of a feature is characterized by its geometrical properties first and non-geometrical properties can be attached to it as subproperties. The advantage of this approach is that we can attach non-geometrical properties to the complete geometry but also to any part of it.

In this encoding root feature elements are named <polygon>, <polyline>... that. Inside this elements,  html text is included describing the feature. We are using microdata to include tag the html text with semantics. In addition, We are introducing the linearRing element that includes the coordinates of the polygon.

The style of the polygon applies to all linearRigns but can be overwritten by one of them. It does on apply to the non-geometrical properties that should define their one styles.

.Example of a polygon encoding
[source,html]
----
<mapml>
  <polygon id="myrestaurant" style="fill:red;stroke:black;stroke-width:3;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <linearRing boundary="exterior">123,321 124,322 126,322 123,321</linearRing>
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
  </polygon>
</mapml>
----

The following example shows how se can add non-geometrical properties to an inner ring.

.Example of a polygon with a ring of a different color and additional non-geometrical properties.
[source,html]
----
<mapml>
  <polygon id="myrestaurant" style="fill:red;stroke:black;stroke-width:3;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <linearRing boundary="exterior">123,321 124,322 126,322 123,321</linearRing>
    <linearRing boundary="interior" style="stroke:orange;stroke-width:5">123.5,321.5 124.5,322.5 125.5,321.5 123.5,321.5
      <p itemprop="description">Hole in the restaurant land.</p>
    </linearRing>
  </polygon>
</mapml>
----

=== Alternative 2: Compact geometry encoding with microdata

.Example of a polygon encoding
[source,html]
----
<mapml>
  <feature id="myrestaurant" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <polygon id="MyRestaurantGeometry" style="fill:red;stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://pending.schema.org/GeospatialGeometry">
      <linearRing boundary="exterior">123,321 124,322 126,322 123,321</linearRing>
    </polygon>
  </feature>
</mapml>
----

=== Alternative 3: GML geometry encoding with microdata
The following encoding reuses GML geometrical classes to encode the geometrical properties. In this case, there is neither namespace nor GML schema but only the reuse of the GML encoding of geometrical features. We are also eliminating the need for defining feature types a priori.The resulting notation is not terrible in terms of size compared to the other more compact alternatives.

Since we have relaxed GML validation, we can consider that GML elements are extensible and we can add attributes and element when needed. One of our additions is the inclusion of style to represent how the objects need to be portrait in the screen. In the following examples we use the style property. We could also use the other approaches to associate styles to elements in HTML such as the use of "class" names or the association of styles to element id's.

[NOTE]
====
The use of SVG (css) styles in GML is not new and was introduced in GML 3.0.0 and still present in the informative annex H in GML 3.2.1. Nevertheless, the encoding suggested here is different and based on how HTML links elements with css styles.
====

.Example of a polygon encoding
[source,html]
----
<mapml>
  <feature id="myrestaurant" style="stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <Polygon id="MyRestaurantGeometry" style="fill:lime;stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://www.opengis.net/gml/3.2">
      <exterior>
        <LinearRing>
          <posList>123 321 124 322 126 322 123 321
          </posList>
        </LinearRing>
      </exterior>
    </Polygon>
  </feature>
</mapml>
----

In this example, we making use of the relaxation of GML validation to include new style attribute to in inner ring and to add non-geometrical properties to it.

.Example of a polygon encoding with holes
[source,html]
----
<mapml>
  <feature id="myrestaurant" style="stroke:black;stroke-width:5;opacity:0.5" itemscope itemtype="http://schema.org/Restaurant">
    <h1 itemprop="name">Fondue for Fun and Fantasy</h1>
    <p itemprop="description">Fantastic and fun for all your cheesy occasions.</p>
    <p>Open: <span itemprop="openingHours" content="Mo,Tu,We,Th,Fr,Sa,Su 11:30-23:00">Daily from 11:30am till 11pm</span></p>
    <p>Phone: <span itemprop="telephone" content="+155501003333">555-0100-3333</span></p>
    <p>View <a itemprop="menu" href="http://example.com/menu">our menu</a>.</p>
    <Polygon id="MyRestaurantGeometry" style="fill:lime;stroke:black;stroke-width:3;opacity:0.5" itemscope itemtype="http://www.opengis.net/gml/3.2">
      <exterior>
        <LinearRing>
          <posList>123 321 124 322 126 322 123 321
          </posList>
        </LinearRing>
      </exterior>
      <interior style="stroke:orange;stroke-width:5">
        <LinearRing>
          <posList>123.5 321.5 124.5 322.5 125.5 321.5 123.5 321.5
          </posList>
        </LinearRing>
        <span itemscope itemtype="http://schema.org/Thing">
          <p itemprop="description">Hole in the restaurant land.</p>
        </span>
      </interior>
    </Polygon>
  </feature>
</mapml>
----

If we opt for this approach, we should detail what extensions are allowed in the specification. In addition, we could need some addition to GML objects, such as the addition of ellipses.
