[[styles]]
== CCS Symbolization

CSS stands for Cascading Style Sheets. CSS describes how HTML elements are to be displayed on screen. A CSS is a sequence of rule-sets the consist of two parts

* The selector, that points to the HTML element to be symbolized
* The declaration block that contains one or more symbol declarations

.Example of a ruleset in CSS
[source,css]
----
p {
    color: red;
    text-align: center;
}
----

In the example the _selector_ points to all <p> elements and declares the letters will be _red_ and paragraph will be _centered_.

=== How to apply css styles to geometries
The more direct way to apply ccs symbolization is to do it inline

.Example of a polygon encoding
[source,html]
----
<polygon style="fill:red;stroke:black;stroke-width:5;opacity:0.5">
...
</polygon>
----

Another direct way to set styles is to use class (or id) to assign a css ruleset.

[source,html]
----
<style>
.nice
{
  fill:red;stroke:black;stroke-width:5;opacity:0.5
}
</style>

<polygon class="nice">
...
</polygon>
----

CSS has a way to select elements to be symbolized depending on the values of some attributes of the element.

[source,html]
----
<style>
polygon[type="road"]
{
  fill:red;stroke:black;stroke-width:5;opacity:0.5
}
</style>

<polygon type="road">
...
</polygon>
----

CSS has selectors that can be used to select element tag names, class attributes or elements id's. An interesting capability is that selectors can be used to select whatever element name that has an attribute (using the '*' character).

[source,html]
----
<style>
*[type="road"]{
    background:red;
}
</style>
<feature>
  <properties>
    <span type="road">road</span>
  </properties>
</feature>
----

As suggested by https://www.brmwebdev.com/dev/css/schema-based-styling, we can use this to select elements of a particular itemtype. Going further in this approach, we can select itemtype's that are in a particular scope. I have not been ale to find anyone suggesting that, but it is what you should do if you want to be precise in your selectors. This approach was already mentioned in OGC 16-053r1.

[source,html]
----
<style>
*[itemtype="http://www.opengis.net/road"] [itemprop="type"]{
    background:red;
}
</style>
<feature>
  <properties>
    <div itemscope itemtype="http://www.opengis.net/road">
      <span itemprop="type">road</span>
    </div>
  </properties>
</feature>
----

Exploring the combinations of all this possible combinations together, and analyzing what is possible in CSS, we can found some important limitations in CSS that prevents us from doing things that are common in GIS such us conditioning the style of a geometry to some values of the properties or specify a style declaration value as function of a property value.

=== Limitations in CSS
In the experimentation done to apply CCS to features with properties and geometry, we have detected the following limitations:name: value

* You cannot set select an element of the HTML and apply the symbol to another element
* You cannot set a selector based on the value of the element (you can do it based on an attribute of the element)
* You cannot set a selector based on the value of two properties at the same level.
* You cannot set a symbol declaration value (e.g. _width_ ) as a function of a value of an element or attribute in the HTML

It seems that the limitations in the selectors syntax where imposed to allow a faster parser of the HTML-CSS styler.

==== You cannot set a selector based on the value of the element.
CSS selectors can only select elements based attributes but not on element values (a.k.a element innerHTML). The use of the attribute "content" of microdata could be a fix to this limitation even if we are forced to repeat the value.

[source,html]
----
<style>
*[itemtype="http://www.opengis.net/road"] [itemprop="theme"][content="road"]{
    background:red;
}
</style>
<feature>
  <properties>
      <table a="b" class="table-properties" itemscope itemtype="http://www.opengis.net/road">
        <tbody>
          <tr>
            <th scope="row">id</th>
            <td itemprop="id">10964418e33d457aabd6f6ab10dc2e4a</td>
          </tr>
          <tr>
            <th scope="row">theme</th>
            <td itemprop="theme" content="road">road</td>
          </tr>
        </tbody>
      </table>
  </properties>
  <geometry>
     <polygon>
     </polygon>
  </geometry>
</feature>
----

To avoid the need to repeat the content as an _attribute_ and as a _value_, you could use CSS content property as suggested here: https://www.w3schools.com/cssref/pr_gen_content.asp. In the following example, we populate the innerHTML span element with the content of the  _content_ attribute using the CSS declaration _content_.

[source,html]
----
<html>
<style>
feature *[itemtype="http://www.opengis.net/road"] [itemprop="theme"][content="highway"] {
    background:red;
}

feature *[itemtype="http://www.opengis.net/road"] [itemprop="theme"]::after {
    content: attr(content);
}
</style>
<feature>
  <properties>
    <div itemscope itemtype="http://www.opengis.net/road">
      <span itemprop="theme" content="highway"></span>
  </properties>
</feature>
----
==== You cannot set select an element of the HTML and apply the symbol to another element
In principle, CSS was not designed to select some elements but apply the style to another element. In our case, this means that in general it is not possible to define a selector depending on "properties" and apply this to "geometry".
The only approximation to this behavior is to select the polygon that is a child of geometry that has a _precedent sibling_ (using ~) with an attribute value. It is still possible to go into single attribute values (that is what we need).

[source,html]
----
<style>
properties[type="road"] ~ geometry polygon {
    background:red;
}
</style>

<feature>
  <properties type="road">
      <table>
      </table>
  </properties>
  <geometry>
     <polygon>
	polygon
     </polygon>
  </geometry>
</feature>
----

The use of JavaScript can help to overcome this limitation. We can use querySelectorAll to make use of selector of properties and className to apply the style to geometries.

[source,html]
----
<style>
.road_red {
    background:red;
}
</style>
<script>
function setColorsToGeometries()
{
	var roads=document.querySelectorAll('*[itemtype="http://www.opengis.net/road"] [itemprop="theme"][content="road"]');

	for (var i=0; i<roads.length; i++)
	{
		var elem=roads[i];
		while (elem && elem.tagName.toLowerCase()!="properties")
			elem=elem.parentElement;
		elem.parentElement.getElementsByTagName("geometry")[0].className="road_red";
	}
}
</script>

<body onLoad="setColorsToGeometries()">
  <feature>
    <properties>
        <table a="b" class="table-properties" itemscope itemtype="http://www.opengis.net/road">
          <tbody>
            <tr>
              <th scope="row">theme</th>
              <td itemprop="theme" content="road">road</td>
            </tr>
          </tbody>
        </table>
    </properties>
    <geometry>
       <polygon>
       </polygon>
    </geometry>
  </feature>
</body>
----

=== Extensions of CSS to support geospatial requirements
NOTE: We need to study the use of CSS styling as defined in:
•	A quick hands on tutorial from GeoSolutions training materials: https://geoserver.geo-solutions.it/edu/en/pretty_maps/css.html
•	The GeoServer documentation:
o	The getting started tutorial: http://docs.geoserver.org/latest/en/user/styling/css/tutorial.html
o	The "cookbook": http://docs.geoserver.org/latest/en/user/styling/css/cookbook/index.html
o	Full list of supported properties: http://docs.geoserver.org/latest/en/user/styling/css/properties.html
o	Full contents with more links here: http://docs.geoserver.org/latest/en/user/styling/css/index.html
and also in https://carto.com/docs/carto-engine/cartocss/

One of the needed extensions the capability to apply a selector based on some _properties_ values to the _geometry_. Our proposal is to incorporate _condition1_ attribute to point another selector that will add extra conditions based on elements that are not directly the ones to simbolize. Both the _selector_ and the _condition1_ should be of the same father.

A suggested possibility is:

[source,html]
----
<style>
feature polygon; condition1: feature *[itemtype="http://www.opengis.net/road"] [itemprop="theme"][content="road"]
{
    background:red;
}
</style>
<feature>
  <properties>
      <table a="b" class="table-properties" itemscope itemtype="http://www.opengis.net/road">
        <tbody>
          <tr>
            <th scope="row">id</th>
            <td itemprop="id">10964418e33d457aabd6f6ab10dc2e4a</td>
          </tr>
          <tr>
            <th scope="row">theme</th>
            <td itemprop="theme" content="road">road</td>
          </tr>
        </tbody>
      </table>
  </properties>
  <geometry>
     <polygon>
     </polygon>
  </geometry>
</feature>
----

Another extension iscould be to condition a declaration value (e.g. width) to a property value (e.g. lanes). This could be achieved by using a selector as a value of a symbol declaration:

[source,html]
----
<style>
feature polygon; condition1: feature *[itemtype="http://www.opengis.net/road"] [itemprop="theme"][content="road"]
{
    background:red;
    label: feature *[itemtype="http://www.opengis.net/road"] [itemprop="name"][content];
    stroke-width: feature *[itemtype="http://www.opengis.net/road"] [itemprop="lanes"][content];
}
</style>

<feature>
  <properties>
      <table a="b" class="table-properties" itemscope itemtype="http://www.opengis.net/road">
        <tbody>
          <tr>
            <th scope="row">id</th>
            <td itemprop="id">10964418e33d457aabd6f6ab10dc2e4a</td>
          </tr>
          <tr>
            <th scope="row">theme</th>
            <td itemprop="theme" content="road">road</td>
          </tr>
          <tr>
            <th scope="row">theme</th>
            <td itemprop="name" content="route 66">Route 66</td>
          </tr>
          <tr>
            <th scope="row">theme</th>
            <td itemprop="lanes" content="3">3</td>
          </tr>
        </tbody>
      </table>
  </properties>
  <geometry>
     <polygon>
     </polygon>
  </geometry>
</feature>
----
